version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.3-node-browsers
    working_directory: ~/simplecov-material

    steps:
      - checkout
